# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto for package 'opentelemetry.proto.collector.profiles.v1development'
# Original file comments:
# Copyright 2023, OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'opentelemetry/proto/collector/profiles/v1development/profiles_service_pb'

module Opentelemetry
  module Proto
    module Collector
      module Profiles
        module V1development
          module ProfilesService
            # Service that can be used to push profiles between one Application instrumented with
            # OpenTelemetry and a collector, or between a collector and a central collector.
            class Service

              include ::GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'opentelemetry.proto.collector.profiles.v1development.ProfilesService'

              rpc :Export, ::Opentelemetry::Proto::Collector::Profiles::V1development::ExportProfilesServiceRequest, ::Opentelemetry::Proto::Collector::Profiles::V1development::ExportProfilesServiceResponse
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
